export const SYMPTOMS = [
  { id: 0, symptom: 'itching' },
  { id: 1, symptom: 'skin rash' },
  { id: 2, symptom: 'nodal skin eruptions' },
  { id: 3, symptom: 'continuous sneezing' },
  { id: 4, symptom: 'shivering' },
  { id: 5, symptom: 'chills' },
  { id: 6, symptom: 'joint pain' },
  { id: 7, symptom: 'stomach pain' },
  { id: 8, symptom: 'acidity' },
  { id: 9, symptom: 'ulcers on tongue' },
  { id: 10, symptom: 'muscle wasting' },
  { id: 11, symptom: 'vomiting' },
  { id: 12, symptom: 'burning micturition' },
  { id: 13, symptom: 'spotting  urination' },
  { id: 14, symptom: 'fatigue' },
  { id: 15, symptom: 'weight gain' },
  { id: 16, symptom: 'anxiety' },
  { id: 17, symptom: 'cold hands and feets' },
  { id: 18, symptom: 'mood swings' },
  { id: 19, symptom: 'weight loss' },
  { id: 20, symptom: 'restlessness' },
  { id: 21, symptom: 'lethargy' },
  { id: 22, symptom: 'patches in throat' },
  { id: 23, symptom: 'irregular sugar level' },
  { id: 24, symptom: 'cough' },
  { id: 25, symptom: 'high fever' },
  { id: 26, symptom: 'sunken eyes' },
  { id: 27, symptom: 'breathlessness' },
  { id: 28, symptom: 'sweating' },
  { id: 29, symptom: 'dehydration' },
  { id: 30, symptom: 'indigestion' },
  { id: 31, symptom: 'headache' },
  { id: 32, symptom: 'yellowish skin' },
  { id: 33, symptom: 'dark urine' },
  { id: 34, symptom: 'nausea' },
  { id: 35, symptom: 'loss of appetite' },
  { id: 36, symptom: 'pain behind the eyes' },
  { id: 37, symptom: 'back pain' },
  { id: 38, symptom: 'constipation' },
  { id: 39, symptom: 'abdominal pain' },
  { id: 40, symptom: 'diarrhoea' },
  { id: 41, symptom: 'mild fever' },
  { id: 42, symptom: 'yellow urine' },
  { id: 43, symptom: 'yellowing of eyes' },
  { id: 44, symptom: 'acute liver failure' },
  { id: 45, symptom: 'fluid overload' },
  { id: 46, symptom: 'swelling of stomach' },
  { id: 47, symptom: 'swelled lymph nodes' },
  { id: 48, symptom: 'malaise' },
  { id: 49, symptom: 'blurred and distorted vision' },
  { id: 50, symptom: 'phlegm' },
  { id: 51, symptom: 'throat irritation' },
  { id: 52, symptom: 'redness of eyes' },
  { id: 53, symptom: 'sinus pressure' },
  { id: 54, symptom: 'runny nose' },
  { id: 55, symptom: 'congestion' },
  { id: 56, symptom: 'chest pain' },
  { id: 57, symptom: 'weakness in limbs' },
  { id: 58, symptom: 'fast heart rate' },
  { id: 59, symptom: 'pain during bowel movements' },
  { id: 60, symptom: 'pain in anal region' },
  { id: 61, symptom: 'bloody stool' },
  { id: 62, symptom: 'irritation in anus' },
  { id: 63, symptom: 'neck pain' },
  { id: 64, symptom: 'dizziness' },
  { id: 65, symptom: 'cramps' },
  { id: 66, symptom: 'bruising' },
  { id: 67, symptom: 'obesity' },
  { id: 68, symptom: 'swollen legs' },
  { id: 69, symptom: 'swollen blood vessels' },
  { id: 70, symptom: 'puffy face and eyes' },
  { id: 71, symptom: 'enlarged thyroid' },
  { id: 72, symptom: 'brittle nails' },
  { id: 73, symptom: 'swollen extremeties' },
  { id: 74, symptom: 'excessive hunger' },
  { id: 75, symptom: 'extra marital contacts' },
  { id: 76, symptom: 'drying and tingling lips' },
  { id: 77, symptom: 'slurred speech' },
  { id: 78, symptom: 'knee pain' },
  { id: 79, symptom: 'hip joint pain' },
  { id: 80, symptom: 'muscle weakness' },
  { id: 81, symptom: 'stiff neck' },
  { id: 82, symptom: 'swelling joints' },
  { id: 83, symptom: 'movement stiffness' },
  { id: 84, symptom: 'spinning movements' },
  { id: 85, symptom: 'loss of balance' },
  { id: 86, symptom: 'unsteadiness' },
  { id: 87, symptom: 'weakness of one body side' },
  { id: 88, symptom: 'loss of smell' },
  { id: 89, symptom: 'bladder discomfort' },
  { id: 90, symptom: 'foul smell of urine' },
  { id: 91, symptom: 'continuous feel of urine' },
  { id: 92, symptom: 'passage of gases' },
  { id: 93, symptom: 'internal itching' },
  { id: 94, symptom: 'toxic look (typhos)' },
  { id: 95, symptom: 'irritability' },
  { id: 96, symptom: 'muscle pain' },
  { id: 97, symptom: 'altered sensorium' },
  { id: 98, symptom: 'red spots over body' },
  { id: 99, symptom: 'belly pain' },
  { id: 100, symptom: 'abnormal menstruation' },
  { id: 101, symptom: 'dischromic  patches' },
  { id: 102, symptom: 'watering from eyes' },
  { id: 103, symptom: 'increased appetite' },
  { id: 104, symptom: 'polyuria' },
  { id: 105, symptom: 'family history' },
  { id: 106, symptom: 'mucoid sputum' },
  { id: 107, symptom: 'rusty sputum' },
  { id: 108, symptom: 'lack of concentration' },
  { id: 109, symptom: 'visual disturbances' },
  { id: 110, symptom: 'receiving blood transfusion' },
  { id: 111, symptom: 'receiving unsterile injections' },
  { id: 112, symptom: 'coma' },
  { id: 113, symptom: 'stomach bleeding' },
  { id: 114, symptom: 'distention of abdomen' },
  { id: 115, symptom: 'history of alcohol consumption' },
  { id: 116, symptom: 'fluid overload' },
  { id: 117, symptom: 'blood in sputum' },
  { id: 118, symptom: 'prominent veins on calf' },
  { id: 119, symptom: 'palpitations' },
  { id: 120, symptom: 'painful walking' },
  { id: 121, symptom: 'pus filled pimples' },
  { id: 122, symptom: 'blackheads' },
  { id: 123, symptom: 'scurring' },
  { id: 124, symptom: 'skin peeling' },
  { id: 125, symptom: 'silver like dusting' },
  { id: 126, symptom: 'small dents in nails' },
  { id: 127, symptom: 'inflammatory nails' },
  { id: 128, symptom: 'blister' },
  { id: 129, symptom: 'red sore around nose' },
  { id: 130, symptom: 'yellow crust ooze' },
  { id: 131, symptom: 'sadness' },
  { id: 132, symptom: 'anger' },
  { id: 133, symptom: 'sleep disturbances' },
  { id: 134, symptom: 'tiredness' },
  { id: 135, symptom: 'guilt' },
  { id: 136, symptom: 'trouble remembering things' },
  { id: 137, symptom: 'thoughts of death' },
  { id: 138, symptom: 'loss of interest' },
];
